microwave/rollingpin fix
Rampoch/Chaotic-Onyx pull request #151
Opened 2018-05-17 02:05 UTC by LagannPM

Микроволновка принимает стак предметов с размер в 1 еденицу(раньше принимала только если в стаке больше 1)
Скалка теперь звучит не как режущее

2018-05-17 18:22 UTC, Epicus7 requested changes

2018-05-17 18:22 UTC, Epicus7 commented on code/game/machinery/kitchen/microwave.dm
> +
Эти изменения нужно убрать

2018-05-17 18:22 UTC, Epicus7 commented on code/game/machinery/kitchen/microwave.dm
> +			else
>Микроволновка принимает стак предметов с размер в 1 единицу

Это не так работает.

Насколько я вижу, сейчас у тебя если больше единицы, то добавляется в микроволновку. А если один или ноль (так может быть?), то предмет выкинется на пол?

2018-05-17 18:23 UTC, Epicus7 commented
Еще надо убрать скрипты, опять же.

2018-05-18 02:25 UTC, ITCups commented on code/game/machinery/kitchen/microwave.dm
> +			else
"выкидывает" в микроволновку.
`user.drop_item(src)` где (src) это указатель на микроволновку
Я тестил и без проверки не коммичу
И ноль не может быть так как он бы не прошел проверку выше

2018-05-18 02:40 UTC, LagannPM commented on code/game/machinery/kitchen/microwave.dm
> +			else
по сути `S.use(1)` это использовать один предмет из стака, но я не знал будут ли проблемы со стаком если я доюзаю его до нуля. Решил не рисковать и запихнул все оставшиеся в микроволновку. Для не стаковых предметов везде используется `user.drop_item(src)`

2018-05-25 06:04 UTC, closed without merging