Добавил возможность изменять цвета кепкам в лодауте
Rampoch/Chaotic-Onyx pull request #249
Opened 2018-07-07 11:17 UTC by Error777

Теперь доступно выбрать тип кепки и изменить ее цвет.

2018-07-07 21:20 UTC, PlinHost requested changes
Левые шапки под раздачу попали.

2018-07-07 21:20 UTC, PlinHost commented on code/modules/client/preference_setup/loadout/lists/headwear.dm
> -	caps["flat cap"] = /obj/item/clothing/head/flatcap
Раз.

2018-07-07 21:20 UTC, PlinHost commented on code/modules/client/preference_setup/loadout/lists/headwear.dm
> -	caps["mailman cap"] = /obj/item/clothing/head/mailman
Два.

2018-07-08 19:34 UTC, Error777 commented
Закрою и переделаю.

2018-07-08 19:34 UTC, closed without merging