Fix resolve #276 and resolve #259
Rampoch/Chaotic-Onyx pull request #283
Opened 2018-07-25 08:53 UTC by straelok

resolve #259
Added checking before causing flash damage.
resolve #276
Commented an unknown part of the code that provoked it. (Tested)

2018-07-26 01:43 UTC, Epicus7 requested changes

2018-07-26 01:43 UTC, Epicus7 commented on code/game/objects/items/weapons/tools.dm
> +		if(!E || E.name == "optical sensor")
Ну мы же решили, что тут лучше будет добавить в глаза новую переменную, которая отвечает за эту восприимчивость. И проверять здесь не имя, а эту переменную на то TRUE она или FALSE.

2018-07-26 01:43 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human.dm
> +	if(usr.stat || usr.restrained() || !isliving(usr) || !ishuman(usr)) return
Эти изменения затесались со старого коммита.

При работе с ГитХабом лучше делать так:
1. Создаешь новую ветку в своем форке на гитхабе под конкретный ПР. Обновляешь под нужную тебе версию (последнюю обычно, но это не обязательно).
2. Вносишь туда все свои изменения коммитами.
3. Делаешь ПР этой ветки в основную ветку нашего репозитория.
4. Я ПР принимаю.
5. Удаляешь свою ветку и делаешь новую под новый ПР. <-- вот в этом пункте твои локальные изменения сносятся и ты можешь их перекачать уже с нашего репозитория, куда я их принял.

Если пытаться дальше делать что-то в своей ветке, то начнутся конфликты твоих изменений в твоем форке с твоими же изменениями у нас в репе.

2018-07-26 01:43 UTC, Epicus7 commented on code/modules/assembly/proximity.dm
> +*/
Я так понимаю, эти изменения вообще ломают проксимити-сенсор. Как бы его суть в том, что он должен подавать сигнал в тот момент, когда к нему кто-то подходит. Это функция отвечает за подачу сигнала. Если ее выпилить, то вместо нее будет вызываться родительская /atom/proc/HasProximity, которая пустая.

2018-07-26 01:48 UTC, straelok commented on code/modules/assembly/proximity.dm
> +*/
Нет, функции /obj/item/device/assembly/prox_sensor/Process() отвечает за вызов sense() при движении.

2018-07-26 01:51 UTC, straelok commented on code/game/objects/items/weapons/tools.dm
> +		if(!E || E.name == "optical sensor")
Если в глаз добавить по человечески параметр "защиты от яркого света" (который используется в проверках на вспышках) то то компилятор дает OwerWrite на родителя. Добавить новую переменную? А стоит ли?

2018-07-26 02:18 UTC, Epicus7 commented on code/game/objects/items/weapons/tools.dm
> +		if(!E || E.name == "optical sensor")
Я понял, да, там есть поле innate_flash_protection = FLASH_PROTECTION_NONE

Давай робоглазам пропишем
innate_flash_protection = FLASH_PROTECTION_MODERATE

Возможно, это будет немного имбалансно, ибо защитит еще от других вспышек разных, но, если что, подкрутим потом. И проверку, соответственно, что это переменная > 0.

У тебя, возможно, ошибка выпадает из-за того, что ты пишешь
**var/**innate_flash_protection = FLASH_PROTECTION_MODERATE
Если так писать, то у тебя как бы идет определение. Если без var, то ты просто задаешь значение для переменной, которая уже была определена.

2018-07-26 02:20 UTC, Epicus7 commented on code/modules/assembly/proximity.dm
> +*/
Окей

2018-07-26 02:21 UTC, straelok commented on code/game/objects/items/weapons/tools.dm
> +		if(!E || E.name == "optical sensor")
Да, писал через var/, понял.
Сегодня переделаю нормально тогда.
Про проверку - не понял...

2018-07-26 02:22 UTC, Epicus7 commented on code/game/objects/items/weapons/tools.dm
> +		if(!E || E.name == "optical sensor")
Ну эти дефайны вот как выглядят:
#define FLASH_PROTECTION_VULNERABLE -2
#define FLASH_PROTECTION_REDUCED -1
#define FLASH_PROTECTION_NONE 0
#define FLASH_PROTECTION_MODERATE 1
#define FLASH_PROTECTION_MAJOR 2

Соответственно, нам не нужно наносить урон от вспышки сварочного аппарата, если защита > 0.

2018-07-26 02:23 UTC, straelok commented on code/modules/assembly/proximity.dm
> +*/
Но вопрос, что делает /obj/item/device/assembly/prox_sensor/HasProximity(atom/movable/AM as mob|obj) все еще актуален... Ибо я в ней смысла не нашел, но сама функция вызывается крайне часто, но попадает под условия выхода из функции. Sense() же в этой функции срабатывает только на призрака ( по личным наблюдениям ). Спровоцировать вызов sense() в этой функции чем либо еще я не смог.

2018-07-26 02:25 UTC, straelok commented on code/game/objects/items/weapons/tools.dm
> +		if(!E || E.name == "optical sensor")
Если я не ошибаюсь, если у тебя глаза повреждены более чем на 10 едениц то MODERATE тоже наносит небольшой урон (точно не помню). Мне же по идеи в алгоритме нанесения урона от вспышек вообще нечего не стоит трогать... Там и так все ок вроде бы. Только уровень защиты глаз поменять.

2018-07-26 02:28 UTC, Epicus7 commented on code/game/objects/items/weapons/tools.dm
> +		if(!E || E.name == "optical sensor")
Ну может быть. Но просто проверка по названию - это очень ненадежно. Тогда уж лучше хотя бы по типу сделать, а не по названию. А то мало ли, кому что в голову взбредет там поменять. Если тип исчезнет, то ошибка будет, а если название поменяют, то никто даже и не заметит.

2018-07-26 02:28 UTC, Epicus7 commented on code/modules/assembly/proximity.dm
> +*/
Возможно, это опять дублирующий код. Не знаю, разбираться надо.

2018-07-26 02:30 UTC, straelok commented on code/modules/assembly/proximity.dm
> +*/
Он больше похож на дебаггер чей-то или на очень кривой фикс чего-то.
Пусть остается в комменте.

2018-08-06 17:50 UTC, Epicus7 commented
Приняли другим ПРом

2018-08-06 17:50 UTC, closed without merging